### ISSUE TITLE
Cloud deploy guide

### ISSUE THREAD

**Issue by Vojtak42** [DSFdsfWxp/savemaster#1]
Hi, could you please write a more detailed guide on how to deploy the project on cloudflare. It would save a great amount of time for others.
Tjank you

**Comment by DSFdsfWxp** [comment]
Done.

**Comment by Vojtak42** [comment]
Hi, thanks for the guide but just figuring out that the variable name in KV namespace binding shouldn't be `key` took be a while I was trying either to assigning it to both (which isnt allowed) or just to one of them. Maybe you cloud clarify that in the guide.
Thanks

**Comment by DSFdsfWxp** [comment]
Oh, sorry. I just forgot something in guide. Fixed now.
